---
title: "ReadMe.md"
author: "oavasquez20"
date: "31-10-2020"
output: html_document
---

Getting and Cleaning Data Course Project

This repository is a submission for Getting and Cleaning Data course project. 
It has the instructions on how to run analysis on Human Activity recognition dataset.
Dataset: Human Activity Recognition Using Smartphones
Files:
  CodeBook.md a code book that describes files, variables, data and Extraction transformations and Load (ETL) to achieve the goal
  run_analysis.R performs the data preparation and then followed by the 5 steps described in the course project’s definition:
        Merges the training and the test sets to create one data set.
        Extracts only the measurements on the mean and standard deviation for each measurement.
        Uses descriptive activity names to name the activities in the data set
        Appropriately labels the data set with descriptive variable names.
        From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

    FinalTidyData.txt is the exported final data after all process.
